# Generated by Django 5.0.2 on 2025-01-18 18:44

import tasks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="scheduled_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Запланированное время выполнения"
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="created_at",
            field=models.DateTimeField(
                default=tasks.models.get_moscow_time, verbose_name="Дата создания"
            ),
        ),
    ]
