# Generated by Django 5.0.2 on 2025-01-18 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_task_scheduled_at_alter_task_created_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="scheduled_at",
        ),
    ]
