# Generated by Django 5.0.2 on 2025-01-18 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0003_remove_task_scheduled_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="created_at",
            field=models.DateTimeField(auto_created=True, verbose_name="Дата создания"),
        ),
    ]
